apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-operator
  namespace: ldap-operator
  labels:
    app.kubernetes.io/name: ldap-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ldap-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: ldap-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: ghcr.io/gpu-ninja/ldap-operator:latest
        command:
        - /manager
        args:
        - --leader-elect
        ports:
        - name: metrics
          containerPort: 8080
        - name: healthz
          containerPort: 8081
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
