---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openldap-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapdirectories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapdirectories/finalizers
  verbs:
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapdirectories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapgroups/finalizers
  verbs:
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldaporganizationalunits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.symas.com
  resources:
  - ldaporganizationalunits/finalizers
  verbs:
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldaporganizationalunits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapusers/finalizers
  verbs:
  - update
- apiGroups:
  - openldap.symas.com
  resources:
  - ldapusers/status
  verbs:
  - get
  - patch
  - update
