apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: ldap-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ldap-operator
    app.kubernetes.io/part-of: ldap-operator
  name: ldap-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ldap-manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: ldap-operator
