apiVersion: ldap.gpu-ninja.com/v1alpha1
kind: LDAPDirectory
metadata:
  name: demo
  labels:
    app.kubernetes.io/component: server
spec:
  image: ghcr.io/gpu-ninja/ldap-operator/openldap:latest
  domain: example.com
  organization: "Acme Widgets Inc."
  certificateSecretRef:
    name: demo-tls
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi