//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2023 Damian Peckett <damian@pecke.tt>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	"github.com/gpu-ninja/operator-utils/reference"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPObjectSpec) DeepCopyInto(out *LDAPObjectSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.ParentRef != nil {
		in, out := &in.ParentRef, &out.ParentRef
		*out = new(reference.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPObjectSpec.
func (in *LDAPObjectSpec) DeepCopy() *LDAPObjectSpec {
	if in == nil {
		return nil
	}
	out := new(LDAPObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPServerReference) DeepCopyInto(out *LDAPServerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPServerReference.
func (in *LDAPServerReference) DeepCopy() *LDAPServerReference {
	if in == nil {
		return nil
	}
	out := new(LDAPServerReference)
	in.DeepCopyInto(out)
	return out
}
